services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5001


  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    #volumes:
      #- ./frontend:/app
    command: npm start
